# Generated by Django 4.1.7 on 2023-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_bio_country_alter_bio_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='country',
            field=models.CharField(blank=True, default='Nepal', max_length=10, null=True),
        ),
    ]
